#!/usr/bin/env bash
# Package source folders into separate review/upload archives.
# Safe to re-run: existing zips in the repo root are overwritten.
#
# Usage (from repo root):
#   ./zip-source.sh
#
# ---------------------------------------------------------------------------
# .zipignore reference — excluded from every standard package unless noted
# ---------------------------------------------------------------------------
# node_modules/          npm/yarn/pnpm install trees (not needed for review)
# .git/                  VCS metadata
# dist/                  generic build output
# build/                 generic build output (Create React App, etc.)
# .next/                 Next.js build cache and server bundles
# out/                   Next.js static export output
# .turbo/                Turborepo cache
# coverage/              test coverage reports
# .env                   local secrets / config (never ship)
# .env.*                 env variants (.env.local, .env.production, …)
# *.env                  env files with non-leading-dot names
# .cache/                tool caches (parcel, babel, etc.)
# *.log                  runtime and build logs
# .DS_Store              macOS folder metadata
# package-lock.json      lockfile (large; reproducible via package.json)
# yarn.lock              lockfile
# pnpm-lock.yaml         lockfile
# bun.lockb              lockfile
# *.tsbuildinfo          TypeScript incremental build info
# .eslintcache           ESLint cache
# __pycache__/           Python bytecode cache (worker)
# *.pyc                  compiled Python
# .venv/                 local Python virtualenv
# venv/                  local Python virtualenv
# *.zip                  nested/generated zip artifacts
#
# Terraform packages (infra/ → terraform.zip) include ONLY:
#   *.tf
#   *.tfvars.example
# and additionally exclude:
#   .terraform/          provider/plugin download dir
#   *.tfstate            live state (secrets)
#   *.tfstate.*          state backups
#   *.tfplan             saved plan binaries
#   .terraform.lock.hcl  provider lock (regenerated by terraform init)
#   *.tfvars             real variable files (keep .example only)
# ---------------------------------------------------------------------------

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

# Source directories to package (one zip each). Add new entries in both arrays.
SOURCE_FOLDERS=(
  frontend
  backend
  infra     # IaC lives here; archived as terraform.zip (see ZIP_NAMES)
  worker
)

# Output zip stem for each SOURCE_FOLDERS entry (${stem}.zip written to repo root).
ZIP_NAMES=(
  frontend
  backend
  terraform
  worker
)

if ((${#SOURCE_FOLDERS[@]} != ${#ZIP_NAMES[@]})); then
  echo "error: SOURCE_FOLDERS and ZIP_NAMES must have the same length" >&2
  exit 1
fi

# Zip stems that receive Terraform-only filtering (see zip_terraform_package).
TERRAFORM_ZIP_STEMS=(terraform)

# Exclusion globs passed to zip(1), relative to the folder being archived.
# Each pattern is prefixed with "*/" so nested paths match as well.
COMMON_EXCLUDE_GLOBS=(
  node_modules
  .git
  dist
  build
  .next
  out
  .turbo
  coverage
  .cache
  __pycache__
  .venv
  venv
)

COMMON_EXCLUDE_FILES=(
  .env
  .DS_Store
  package-lock.json
  yarn.lock
  pnpm-lock.yaml
  bun.lockb
)

# Build zip -x arguments from the arrays above.
build_zip_exclude_args() {
  local -n _out=$1
  _out=()
  local glob file

  for glob in "${COMMON_EXCLUDE_GLOBS[@]}"; do
    _out+=(-x "${glob}/*" -x "*/${glob}/*")
  done

  for file in "${COMMON_EXCLUDE_FILES[@]}"; do
    _out+=(-x "${file}" -x "*/${file}")
  done

  # Env files: .env.* and *.env at any depth
  _out+=(-x ".env.*" -x "*/.env.*" -x "*.env" -x "*/*.env")

  # Logs, TS/eslint caches, Python bytecode, nested zips
  _out+=(
    -x "*.log" -x "*/*.log"
    -x "*.tsbuildinfo" -x "*/*.tsbuildinfo"
    -x ".eslintcache" -x "*/.eslintcache"
    -x "*.pyc" -x "*/*.pyc"
    -x "*.zip" -x "*/*.zip"
  )
}

is_terraform_package() {
  local stem=$1
  local t
  for t in "${TERRAFORM_ZIP_STEMS[@]}"; do
    if [[ "$stem" == "$t" ]]; then
      return 0
    fi
  done
  return 1
}

# Standard folder: zip everything under src_dir with shared exclusions.
zip_standard_package() {
  local src_dir=$1
  local dest_zip=$2
  local -a exclude_args=()
  build_zip_exclude_args exclude_args

  (
    cd "$src_dir"
    # -FS sync: drop entries from an existing archive that are no longer on disk.
    zip -r -FS "$dest_zip" . "${exclude_args[@]}"
  )
}

# Terraform/IaC folder: include only review-safe source files.
zip_terraform_package() {
  local src_dir=$1
  local dest_zip=$2
  local -a rel_files=()
  local file relpath

  while IFS= read -r -d '' file; do
    relpath="${file#"${src_dir}/"}"
    rel_files+=("$relpath")
  done < <(
    find "$src_dir" -type f \( -name '*.tf' -o -name '*.tfvars.example' \) \
      ! -path '*/.terraform/*' \
      ! -name '*.tfstate' \
      ! -name '*.tfstate.*' \
      ! -name '*.tfplan' \
      ! -name '.terraform.lock.hcl' \
      ! -name '*.tfvars' \
      -print0
  )

  if ((${#rel_files[@]} == 0)); then
    echo "  warning: no .tf or .tfvars.example files found under ${src_dir}; skipping zip"
    return 0
  fi

  (
    cd "$src_dir"
    zip -r -FS "$dest_zip" "${rel_files[@]}"
  )
}

human_size() {
  local path=$1
  if [[ ! -f "$path" ]]; then
    echo "—"
    return
  fi
  # macOS and GNU du both support -h
  du -h "$path" | cut -f1 | tr -d ' '
}

declare -a CREATED_ZIPS=()

echo "Packaging source folders from: ${ROOT}"
echo

for i in "${!SOURCE_FOLDERS[@]}"; do
  folder="${SOURCE_FOLDERS[$i]}"
  zip_stem="${ZIP_NAMES[$i]}"
  src_path="${ROOT}/${folder}"
  dest_zip="${ROOT}/${zip_stem}.zip"

  echo "→ ${folder}/  →  ${zip_stem}.zip"

  if [[ ! -d "$src_path" ]]; then
    echo "  skipped: directory does not exist"
    echo
    continue
  fi

  rm -f "$dest_zip"

  if is_terraform_package "$zip_stem"; then
    zip_terraform_package "$src_path" "$dest_zip"
  else
    zip_standard_package "$src_path" "$dest_zip"
  fi

  if [[ -f "$dest_zip" ]]; then
    CREATED_ZIPS+=("$dest_zip")
    echo "  created: ${zip_stem}.zip ($(human_size "$dest_zip"))"
  fi
  echo
done

echo "Summary"
echo "-------"
if ((${#CREATED_ZIPS[@]} == 0)); then
  echo "No archives were created."
else
  for z in "${CREATED_ZIPS[@]}"; do
    printf "  %-20s %s\n" "$(basename "$z")" "$(human_size "$z")"
  done
fi
