import type { MockScene } from "@/types/dashboard";

export const MOCK_SCENES: MockScene[] = [
  {
    id: "scene-1",
    title: "Apartment Living Room",
    state: "complete",
    createdAt: "Oct 26, 2023",
    lastModified: "Yesterday",
    thumbnailHue: 260,
  },
  {
    id: "scene-2",
    title: "Office Lobby Concept",
    state: "draft",
    createdAt: "Nov 2, 2023",
    lastModified: "2 days ago",
  },
  {
    id: "scene-3",
    title: "Mountain Resort Model",
    state: "processing",
    createdAt: "Nov 8, 2023",
    lastModified: "Today",
    processingProgress: 75,
    thumbnailHue: 200,
  },
  {
    id: "scene-4",
    title: "City Block Scan",
    state: "preprocessing",
    createdAt: "Nov 10, 2023",
    lastModified: "Today",
  },
  {
    id: "scene-5",
    title: "Sculpture Studio",
    state: "complete",
    createdAt: "Sep 14, 2023",
    lastModified: "Oct 1, 2023",
    thumbnailHue: 280,
  },
  {
    id: "scene-6",
    title: "Coastal Villa Exterior",
    state: "complete",
    createdAt: "Aug 3, 2023",
    lastModified: "Sep 20, 2023",
    thumbnailHue: 190,
  },
  {
    id: "scene-7",
    title: "Warehouse Interior",
    state: "draft",
    createdAt: "Jul 18, 2023",
    lastModified: "Aug 5, 2023",
  },
  {
    id: "scene-8",
    title: "Historic Courtyard",
    state: "processing",
    createdAt: "Jun 22, 2023",
    lastModified: "Yesterday",
    processingProgress: 42,
    thumbnailHue: 150,
  },
  {
    id: "scene-9",
    title: "Retail Storefront",
    state: "preprocessing",
    createdAt: "May 30, 2023",
    lastModified: "Today",
  },
  {
    id: "scene-10",
    title: "Garden Pavilion",
    state: "complete",
    createdAt: "Apr 12, 2023",
    lastModified: "May 2, 2023",
    thumbnailHue: 130,
  },
  {
    id: "scene-11",
    title: "Conference Hall",
    state: "draft",
    createdAt: "Mar 8, 2023",
    lastModified: "Mar 28, 2023",
  },
  {
    id: "scene-12",
    title: "Rooftop Terrace",
    state: "complete",
    createdAt: "Feb 1, 2023",
    lastModified: "Feb 14, 2023",
    thumbnailHue: 320,
  },
];
