name: deploy splatial
on:
  push:
    branches:
      - dev
      - staging
      - main
permissions:
  contents: read
  id-token: write
env:
  AWS_REGION: us-east-1
  #AWS_ROLE_ARN: arn:aws:iam::886601940523:role/github-actions-s3-cloudfront-deploy
  SITE_BUCKET_NAME: splatial-dev-openspacenexus-store
  TERRAFORM_DIR: ./infra 
jobs:
  ci:
    name: lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: site/my-app/package-lock.json
      - name: Install Frontend Dependencies
        working-directory: site/my-app
        run: npm ci
      - name: Run Lint
        working-directory: site/my-app
        run: npm run lint 
      # - name: Run Tests
      #   working-directory: site/my-app
      #   run: npm test
      - name: terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0
          terraform_wrapper: false
      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: infra
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: ci
    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set Environment Context
        id: set-env
        run: |
          if [ "${{ github.ref_name }}" = "dev" ]; then
            echo "gh_env=development" >> "$GITHUB_OUTPUT"
            echo "tf_dir=infra/envs/dev" >> "$GITHUB_OUTPUT"
          elif [ "${{ github.ref_name }}" = "staging" ]; then
            echo "gh_env=staging" >> "$GITHUB_OUTPUT"
            echo "tf_dir=infra/envs/staging" >> "$GITHUB_OUTPUT"
          elif [ "${{ github.ref_name }}" = "main" ]; then
            echo "gh_env=production" >> "$GITHUB_OUTPUT"
            echo "tf_dir=infra/envs/prod" >> "$GITHUB_OUTPUT"
          fi
      - name: Configure AWS credentials for Deployment
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::886601940523:role/splatial-${{ github.ref_name == 'main' && 'prod' || github.ref_name }}-github-deploy-role
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Terraform Init & Apply
        working-directory: ${{ steps.set-env.outputs.tf_dir }}
        run: |
          terraform init
          terraform apply -auto-approve
      - name: Read Terraform outputs
        id: tf
        working-directory: ${{ steps.set-env.outputs.tf_dir }}
        run: |
          echo "s3_bucket_name=$(terraform output -raw s3_bucket_name)" >> "$GITHUB_OUTPUT"
          echo "cloudfront_distribution_id=$(terraform output -raw cloudfront_distribution_id)" >> "$GITHUB_OUTPUT"
          echo "site_url=$(terraform output -raw site_url)" >> "$GITHUB_OUTPUT"
          echo "cognito_user_pool_id=$(terraform output -raw cognito_user_pool_id)" >> "$GITHUB_OUTPUT"
          echo "cognito_client_id=$(terraform output -raw cognito_client_id)" >> "$GITHUB_OUTPUT"
          echo "api_endpoint=$(terraform output -raw api_endpoint)" >> "$GITHUB_OUTPUT"
          echo "raw_scenes_bucket_name=$(terraform output -raw raw_scenes_bucket_name)" >> "$GITHUB_OUTPUT"
          echo "scenes_table_name=$(terraform output -raw scenes_table_name)" >> "$GITHUB_OUTPUT"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: site/my-app/package-lock.json
      - name: Install Frontend Dependencies
        working-directory: site/my-app
        run: npm ci
      - name: Build the Frontend artifacts
        working-directory: site/my-app
        run: npm run build
        env:
          NEXT_PUBLIC_AWS_REGION: us-east-1
          NEXT_PUBLIC_USER_POOL_ID: ${{ steps.tf.outputs.cognito_user_pool_id }}
          NEXT_PUBLIC_CLIENT_ID: ${{ steps.tf.outputs.cognito_client_id }}
          NEXT_PUBLIC_API_GATEWAY_URL: ${{ steps.tf.outputs.api_endpoint }}
          NEXT_PUBLIC_RAW_SCENES_BUCKET: ${{ steps.tf.outputs.raw_scenes_bucket_name }}
          NEXT_PUBLIC_SCENES_TABLE: ${{ steps.tf.outputs.scenes_table_name }}
      - name: Sync Static Assets to S3
        working-directory: site/my-app
        run: |
          aws s3 sync ./out s3://${{ steps.tf.outputs.s3_bucket_name }} \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "node_modules/*" \
            --exclude ".terraform/*" \
            --exclude "*.tf" \
            --exclude "*.tfvars" \
            --exclude "README.md"
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ steps.tf.outputs.cloudfront_distribution_id }} \
            --paths "/*"
      - name: Show deployed site URL
        run: |
          echo "Deployed to: ${{ steps.tf.outputs.site_url }}"